# Generated by Django 3.1.5 on 2021-01-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_auto_20210116_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuber',
            old_name='is_featued',
            new_name='is_featured',
        ),
    ]
